export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGOUT = 'LOGOUT'

export const DASHBOARD_ISSUES_REQUEST = 'DASHBOARD_ISSUES_REQUEST'
export const DASHBOARD_ISSUES_RESPONSE = 'DASHBOARD_ISSUES_RESPONSE'

export const PROJECT_ISSUES_REQUEST = 'PROJECT_ISSUES_REQUEST'
export const PROJECT_ISSUES_RESPONSE = 'PROJECT_ISSUES_RESPONSE'

export const ISSUE_REQUEST = 'ISSUE_REQUEST'
export const ISSUE_RESPONSE = 'ISSUE_RESPONSE'

