export const SAMPLE_INCREMENT = 'SAMPLE_INCREMENT'
export const SAMPLE_REQUEST = 'SAMPLE_REQUEST'
export const SAMPLE_RESPONSE = 'SAMPLE_RESPONSE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGOUT = 'LOGOUT'
